default_config:

logger:
  default: info
  logs:
    custom_components.intelbras_solar: debug

# If you need to debug uncomment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
# debugpy:

ffmpeg:
  ffmpeg_bin: /usr/bin/true

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16

intelbras_solar:
  username: !secret intelbras_username
  password: !secret intelbras_password